@file:Suppress("unused")

package com.abnamro.core.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0XFFFF7043)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFD4C6)
internal val md_theme_light_onPrimaryContainer = Color(0xFF282828)
internal val md_theme_light_primaryFixed = Color(0xFFFFE2D9)
internal val md_theme_light_primaryFixedDim = Color(0xFFFFC5B4)
internal val md_theme_light_onPrimaryFixed = Color(0xFF141414)
internal val md_theme_light_onPrimaryFixedVariant = Color(0xFF33160D)
internal val md_theme_light_secondary = Color(0xFFFFD54F)
internal val md_theme_light_onSecondary = Color(0xFF141414)
internal val md_theme_light_secondaryContainer = Color(0xFFFFF3CA)
internal val md_theme_light_onSecondaryContainer = Color(0xFF332B10)
internal val md_theme_light_secondaryFixedDim = Color(0xFFFFEFB9)
internal val md_theme_light_secondaryFixed = Color(0xFFFFF7DC)
internal val md_theme_light_onSecondaryFixed = Color(0xFF332B10)
internal val md_theme_light_onSecondaryFixedVariant = Color(0xFF4D4018)
internal val md_theme_light_tertiary = Color(0xFFFF4081)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFC6D9)
internal val md_theme_light_onTertiaryContainer = Color(0xFF330D1A)
internal val md_theme_light_tertiaryFixed = Color(0xFFFFD9E6)
internal val md_theme_light_tertiaryFixedDim = Color(0xFFFFB3CC)
internal val md_theme_light_onTertiaryFixed = Color(0xFF330D1A)
internal val md_theme_light_onTertiaryFixedVariant = Color(0xFF4D1326)
internal val md_theme_light_error = Color(0xFFE33338)
internal val md_theme_light_errorContainer = Color(0xFFFCE9E9)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF881E21)
internal val md_theme_light_background = Color(0xFFFFFFFF)
internal val md_theme_light_onBackground = Color(0xFF282828)
internal val md_theme_light_outline = Color(0xFF797979)
internal val md_theme_light_inverseSurface = Color(0xFF2C2C2C)
internal val md_theme_light_inverseOnSurface = Color(0xFFFAFAFA)
internal val md_theme_light_inversePrimary = Color(0xFFFFA88E)
internal val md_theme_light_shadow = Color(0xFF282828)
internal val md_theme_light_outlineVariant = Color(0xFFC8C8C8)
internal val md_theme_light_scrim = Color(0xFF282828)
internal val md_theme_light_surface = Color(0xFFFAFAFA)
internal val md_theme_light_onSurface = Color(0xFF282828)
internal val md_theme_light_onSurfaceVariant = Color(0xFF434343)
internal val md_theme_light_surfaceContainerHighest = Color(0xFFEAEAEA)
internal val md_theme_light_surfaceContainerHigh = Color(0xFFF2F2F2)
internal val md_theme_light_surfaceContainer = Color(0xFFEFEFEF)
internal val md_theme_light_surfaceContainerLow = Color(0xFFFAFAFA)
internal val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
internal val md_theme_light_surfaceDim = Color(0xFFEFEFEF)
internal val md_theme_light_surfaceBright = Color(0xFFF4F4F4)

internal val md_theme_light_disable_primary = Color(0x1FFF7043)
internal val md_theme_light_disable_primary_content = Color(0x61FF7043)
internal val md_theme_light_disable_button = Color(0x1F28281F)
internal val md_theme_light_disable_button_content = Color(0x6128281F)

val colorOnSurfaceVariant2 = Color(0xFF656565)
val colorOnSurfaceVariant3 = Color(0xFFDDDDDD)
val colorHomeBackground = Color(0XFFFFE2D9)


// Dark Theme Colors

internal val md_theme_dark_primary = Color(0xFFFF8A65)
internal val md_theme_dark_onPrimary = Color(0xFF330C04)
internal val md_theme_dark_primaryContainer = Color(0xFF5E190E)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFC6B2)
internal val md_theme_dark_primaryFixed = Color(0xFF772A1D)
internal val md_theme_dark_primaryFixedDim = Color(0xFF5E190E)
internal val md_theme_dark_onPrimaryFixed = Color(0xFFFFD4C6)
internal val md_theme_dark_onPrimaryFixedVariant = Color(0xFFFFA08A)

internal val md_theme_dark_secondary = Color(0xFFFFCA28)
internal val md_theme_dark_onSecondary = Color(0xFF332500)
internal val md_theme_dark_secondaryContainer = Color(0xFF4D3A00)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFFFEFB2)
internal val md_theme_dark_secondaryFixed = Color(0xFF614500)
internal val md_theme_dark_secondaryFixedDim = Color(0xFF4D3A00)
internal val md_theme_dark_onSecondaryFixed = Color(0xFFFFEFD9)
internal val md_theme_dark_onSecondaryFixedVariant = Color(0xFFFFD54F)

internal val md_theme_dark_tertiary = Color(0xFFFF80AB)
internal val md_theme_dark_onTertiary = Color(0xFF3A0A20)
internal val md_theme_dark_tertiaryContainer = Color(0xFF5A1833)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFFC2D1)
internal val md_theme_dark_tertiaryFixed = Color(0xFF6D2541)
internal val md_theme_dark_tertiaryFixedDim = Color(0xFF5A1833)
internal val md_theme_dark_onTertiaryFixed = Color(0xFFFFD9E6)
internal val md_theme_dark_onTertiaryFixedVariant = Color(0xFFFF8FB0)

internal val md_theme_dark_error = Color(0xFFFF6D6D)
internal val md_theme_dark_errorContainer = Color(0xFF410002)
internal val md_theme_dark_onError = Color(0xFF410002)
internal val md_theme_dark_onErrorContainer = Color(0xFFFCE9E9)

internal val md_theme_dark_background = Color(0xFF141414)
internal val md_theme_dark_onBackground = Color(0xFFE0E0E0)
internal val md_theme_dark_outline = Color(0xFF8A8A8A)
internal val md_theme_dark_inverseSurface = Color(0xFFF2F2F2)
internal val md_theme_dark_inverseOnSurface = Color(0xFF2C2C2C)
internal val md_theme_dark_inversePrimary = Color(0xFFFF7043)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_outlineVariant = Color(0xFF555555)
internal val md_theme_dark_scrim = Color(0xFF000000)
internal val md_theme_dark_surface = Color(0xFF1C1C1C)
internal val md_theme_dark_onSurface = Color(0xFFE0E0E0)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFBDBDBD)

internal val md_theme_dark_surfaceContainerHighest = Color(0xFF2E2E2E)
internal val md_theme_dark_surfaceContainerHigh = Color(0xFF252525)
internal val md_theme_dark_surfaceContainer = Color(0xFF202020)
internal val md_theme_dark_surfaceContainerLow = Color(0xFF1B1B1B)
internal val md_theme_dark_surfaceContainerLowest = Color(0xFF121212)
internal val md_theme_dark_surfaceDim = Color(0xFF181818)
internal val md_theme_dark_surfaceBright = Color(0xFF3A3A3A)

internal val md_theme_dark_disable_primary = Color(0x1FFF8A65)
internal val md_theme_dark_disable_primary_content = Color(0x61FF8A65)
internal val md_theme_dark_disable_button = Color(0x1F181818)
internal val md_theme_dark_disable_button_content = Color(0x61181818)

val darkColorOnSurfaceVariant2 = Color(0xFF9E9E9E)
val darkColorOnSurfaceVariant3 = Color(0xFF424242)
val darkColorHomeBackground = Color(0xFF4D1E1E)
